apiVersion: apps/v1
kind: Deployment
metadata:
  name: logapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logapp
  template:
    metadata:
      labels:
        app: logapp
    spec:
      containers:
        - name: logapp
          image: venishaadocker/log-sim-app:latest  # Replace with your image if needed
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: "info"

